// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using Foundation;

namespace Notepad
{
	public partial class Find : NSObject
	{
		public Find (IntPtr handle) : base (handle)
		{
		}
	}
}
